#!/bin/bash
cd
cd Documents/
mkdir holberton
cd holberton
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git
sudo apt-get install emacs
sudo apt-get install valgrind
sudo apt-get install ruby
git config --global user.name "lh008"
git config --global user.email paintluis@gmail.com
git clone https://github.com/lh1008/holbertonschool-low_level_programming.git
git clone https://github.com/lh1008/holberton-system_engineering-devops.git
git clone https://github.com/lh1008/holbertonschool-higher_level_programming.git
git clone https://github.com/lh1008/holbertonschool-higher_level_programming-1.git
git clone https://github.com/holbertonschool/Betty.git
cd Betty
sudo ./install.sh
